package com.lcsmilhan.songsphere.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006782)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBE9FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F29)
val md_theme_light_secondary = Color(0xFF006A60)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF74F8E5)
val md_theme_light_onSecondaryContainer = Color(0xFF00201C)
val md_theme_light_tertiary = Color(0xFF765A00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDF96)
val md_theme_light_onTertiaryContainer = Color(0xFF251A00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF231A00)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF231A00)
val md_theme_light_surfaceVariant = Color(0xFFDCE4E9)
val md_theme_light_onSurfaceVariant = Color(0xFF40484C)
val md_theme_light_outline = Color(0xFF70787D)
val md_theme_light_inverseOnSurface = Color(0xFFFFF0CB)
val md_theme_light_inverseSurface = Color(0xFF3C2F00)
val md_theme_light_inversePrimary = Color(0xFF61D4FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006782)
val md_theme_light_outlineVariant = Color(0xFFC0C8CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF61D4FF)
val md_theme_dark_onPrimary = Color(0xFF003545)
val md_theme_dark_primaryContainer = Color(0xFF004D63)
val md_theme_dark_onPrimaryContainer = Color(0xFFBBE9FF)
val md_theme_dark_secondary = Color(0xFF53DBC9)
val md_theme_dark_onSecondary = Color(0xFF003731)
val md_theme_dark_secondaryContainer = Color(0xFF005048)
val md_theme_dark_onSecondaryContainer = Color(0xFF74F8E5)
val md_theme_dark_tertiary = Color(0xFFEEC148)
val md_theme_dark_onTertiary = Color(0xFF3E2E00)
val md_theme_dark_tertiaryContainer = Color(0xFF5A4400)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDF96)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF231A00)
val md_theme_dark_onBackground = Color(0xFFFFE086)
val md_theme_dark_surface = Color(0xFF231A00)
val md_theme_dark_onSurface = Color(0xFFFFE086)
val md_theme_dark_surfaceVariant = Color(0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CC)
val md_theme_dark_outline = Color(0xFF8A9296)
val md_theme_dark_inverseOnSurface = Color(0xFF231A00)
val md_theme_dark_inverseSurface = Color(0xFFFFE086)
val md_theme_dark_inversePrimary = Color(0xFF006782)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF61D4FF)
val md_theme_dark_outlineVariant = Color(0xFF40484C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF264653)